# Generated by Django 2.2.5 on 2019-09-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_howtostep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowToStep',
        ),
    ]
