# Generated by Django 2.2.5 on 2019-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190914_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
