# Generated by Django 2.2.5 on 2019-09-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190914_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
