# Generated by Django 2.2.5 on 2019-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190914_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
