# Generated by Django 2.2.5 on 2019-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190921_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='create_news',
            field=models.BooleanField(default=False),
        ),
    ]
