# Generated by Django 2.2.5 on 2019-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
